In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.metrics import accuracy_score

In [201]:
movies_data = pd.read_csv('movies.dat',sep='::',engine='python',encoding='latin-1')
movies_data.columns = ['MovieID','MovieName','Category']
movies_data.dropna(inplace=True)
movies_data

,MovieID,MovieName,Category
0,2,Jumanji (1995),Adventure|Children's|Fantasy
1,3,Grumpier Old Men (1995),Comedy|Romance
2,4,Waiting to Exhale (1995),Comedy|Drama
3,5,Father of the Bride Part II (1995),Comedy
4,6,Heat (1995),Action|Crime|Thriller
...,...,...,...
3877,3948,Meet the Parents (2000),Comedy
3878,3949,Requiem for a Dream (2000),Drama
3879,3950,Tigerland (2000),Drama
3880,3951,Two Family House (2000),Drama
3881,3952,"Contender, The (2000)",Drama|Thriller

In [202]:
movies_categories = movies_data['Category']

In [203]:
categories = []
for category in movies_categories:
    splitted_categories = category.split('|')
    for cat in splitted_categories:
        if cat not in categories:
            categories.append(cat)

In [204]:
categories

['Adventure',
 "Children's",
 'Fantasy',
 'Comedy',
 'Romance',
 'Drama',
 'Action',
 'Crime',
 'Thriller',
 'Horror',
 'Animation',
 'Sci-Fi',
 'Documentary',
 'War',
 'Musical',
 'Mystery',
 'Film-Noir',
 'Western']

In [205]:
movies_data[[categories]] = 0
movies_data

,MovieID,MovieName,Category,Adventure,Children's,Fantasy,Comedy,Romance,Drama,Action,...,Thriller,Horror,Animation,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
0,2,Jumanji (1995),Adventure|Children's|Fantasy,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,Heat (1995),Action|Crime|Thriller,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3877,3948,Meet the Parents (2000),Comedy,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3878,3949,Requiem for a Dream (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3879,3950,Tigerland (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3880,3951,Two Family House (2000),Drama,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3881,3952,"Contender, The (2000)",Drama|Thriller,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [206]:
for i in movies_data.index:
    for cat in categories:
        if cat in movies_data['Category'][i]:
            movies_data[cat][i] = 1

C:\Users\Awais Tanveer Khan\AppData\Local\Temp\ipykernel_1216\4225725163.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [207]:
movies_data

,MovieID,MovieName,Category,Adventure,Children's,Fantasy,Comedy,Romance,Drama,Action,...,Thriller,Horror,Animation,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
0,2,Jumanji (1995),Adventure|Children's|Fantasy,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,5,Father of the Bride Part II (1995),Comedy,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,6,Heat (1995),Action|Crime|Thriller,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3877,3948,Meet the Parents (2000),Comedy,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3878,3949,Requiem for a Dream (2000),Drama,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3879,3950,Tigerland (2000),Drama,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3880,3951,Two Family House (2000),Drama,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3881,3952,"Contender, The (2000)",Drama|Thriller,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0

In [208]:
movies_data.drop('Category', inplace=True, axis=1)
movies_data

,MovieID,MovieName,Adventure,Children's,Fantasy,Comedy,Romance,Drama,Action,Crime,Thriller,Horror,Animation,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
0,2,Jumanji (1995),1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,3,Grumpier Old Men (1995),0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,4,Waiting to Exhale (1995),0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,5,Father of the Bride Part II (1995),0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,6,Heat (1995),0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3877,3948,Meet the Parents (2000),0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3878,3949,Requiem for a Dream (2000),0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3879,3950,Tigerland (2000),0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3880,3951,Two Family House (2000),0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3881,3952,"Contender, The (2000)",0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0

In [209]:
users_data = pd.read_csv('users.dat',sep='::',engine='python')
users_data.columns = ['UserID','Gender','Age','Occupation','Zip-code']
users_data.dropna(inplace=True)
users_data

      UserID Gender  Age  Occupation Zip-code
0          2      M   56          16    70072
1          3      M   25          15    55117
2          4      M   45           7    02460
3          5      M   25          20    55455
4          6      F   50           9    55117
...      ...    ...  ...         ...      ...
6034    6036      F   25          15    32603
6035    6037      F   45           1    76006
6036    6038      F   56           1    14706
6037    6039      F   45           0    01060
6038    6040      M   25           6    11106

[6039 rows x 5 columns]

In [210]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
users_data['Gender'] = le.fit_transform(users_data['Gender'])
users_data

      UserID  Gender  Age  Occupation Zip-code
0          2       1   56          16    70072
1          3       1   25          15    55117
2          4       1   45           7    02460
3          5       1   25          20    55455
4          6       0   50           9    55117
...      ...     ...  ...         ...      ...
6034    6036       0   25          15    32603
6035    6037       0   45           1    76006
6036    6038       0   56           1    14706
6037    6039       0   45           0    01060
6038    6040       1   25           6    11106

[6039 rows x 5 columns]

In [211]:
ratings_data = pd.read_csv('ratings.dat',sep='::',engine='python')
ratings_data.columns = ['UserID','MovieID','Ratings','TimeStamp']
ratings_data.dropna(inplace=True)
ratings_data

         UserID  MovieID  Ratings  TimeStamp
0             1      661        3  978302109
1             1      914        3  978301968
2             1     3408        4  978300275
3             1     2355        5  978824291
4             1     1197        3  978302268
...         ...      ...      ...        ...
1000203    6040     1091        1  956716541
1000204    6040     1094        5  956704887
1000205    6040      562        5  956704746
1000206    6040     1096        4  956715648
1000207    6040     1097        4  956715569

[1000208 rows x 4 columns]

In [212]:
movies_rating_data = pd.merge(movies_data, ratings_data, on=['MovieID','MovieID'])
movies_rating_data

,MovieID,MovieName,Adventure,Children's,Fantasy,Comedy,Romance,Drama,Action,Crime,...,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western,UserID,Ratings,TimeStamp
0,2,Jumanji (1995),1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,10,5,979168267
1,2,Jumanji (1995),1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,13,3,978202563
2,2,Jumanji (1995),1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,18,2,978152541
3,2,Jumanji (1995),1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,23,2,978461604
4,2,Jumanji (1995),1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,27,1,978129692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998126,3952,"Contender, The (2000)",0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,5812,4,992072099
998127,3952,"Contender, The (2000)",0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,5831,3,986223125
998128,3952,"Contender, The (2000)",0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,5837,4,1011902656
998129,3952,"Contender, The (2000)",0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,5927,1,979852537
998130,3952,"Contender, The (2000)",0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,5998,4,1001781044

In [218]:
data = pd.merge(movies_rating_data, users_data, on=['UserID','UserID'])
data

,MovieID,MovieName,Adventure,Children's,Fantasy,Comedy,Romance,Drama,Action,Crime,...,Mystery,Film-Noir,Western,UserID,Ratings,TimeStamp,Gender,Age,Occupation,Zip-code
0,2,Jumanji (1995),1,1,1,0,0,0,0,0,...,0,0,0,10,5,979168267,0,35,1,95370
1,7,Sabrina (1995),0,0,0,1,1,0,0,0,...,0,0,0,10,4,978227763,0,35,1,95370
2,24,Powder (1995),0,0,0,0,0,1,0,0,...,0,0,0,10,3,978230586,0,35,1,95370
3,32,Twelve Monkeys (1995),0,0,0,0,0,1,0,0,...,0,0,0,10,5,979168160,0,35,1,95370
4,48,Pocahontas (1995),0,1,0,0,1,0,0,0,...,0,0,0,10,4,978230090,0,35,1,95370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998075,3513,Rules of Engagement (2000),0,0,0,0,0,1,0,0,...,0,0,0,5727,4,958489970,1,25,4,92843
998076,3535,American Psycho (2000),0,0,0,1,0,0,0,0,...,0,0,0,5727,2,958489970,1,25,4,92843
998077,3536,Keeping the Faith (2000),0,0,0,1,1,0,0,0,...,0,0,0,5727,5,958489902,1,25,4,92843
998078,3555,U-571 (2000),0,0,0,0,0,0,1,0,...,0,0,0,5727,3,958490699,1,25,4,92843
998079,3578,Gladiator (2000),0,0,0,0,0,1,1,0,...,0,0,0,5727,5,958490171,1,25,4,92843

In [219]:
data.isnull().values.any()

False

In [220]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 998080 entries, 0 to 998079
Data columns (total 27 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   MovieID      998080 non-null  int64
 1   MovieName    998080 non-null  object
 2   Adventure    998080 non-null  int64
 3   Children's   998080 non-null  int64
 4   Fantasy      998080 non-null  int64
 5   Comedy       998080 non-null  int64
 6   Romance      998080 non-null  int64
 7   Drama        998080 non-null  int64
 8   Action       998080 non-null  int64
 9   Crime        998080 non-null  int64
 10  Thriller     998080 non-null  int64
 11  Horror       998080 non-null  int64
 12  Animation    998080 non-null  int64
 13  Sci-Fi       998080 non-null  int64
 14  Documentary  998080 non-null  int64
 15  War          998080 non-null  int64
 16  Musical      998080 non-null  int64
 17  Mystery      998080 non-null  int64
 18  Film-Noir    998080 non-null  int64
 19  Western      998080 non-null  int64
 20  UserID       998080 non-null  int64
 21  Ratings      998080 non-null  int64
 22  TimeStamp    998080 non-null  int64
 23  Gender       998080 non-null  int32
 24  Age          998080 non-null  int64
 25  Occupation   998080 non-null  int64
 26  Zip-code     998080 non-null  object
dtypes: int32(1), int64(24), object(2)
memory usage: 209.4+ MB

In [221]:
ratings = data['Ratings'].value_counts()
numbers = ratings.index
quantity = ratings.values

fig = px.pie(data, values=quantity, names= numbers)
fig.show()

In [222]:
data[data['Ratings'] == 5]['MovieName'].value_counts().head(10)

American Beauty (1999)                                   1963
Star Wars: Episode IV - A New Hope (1977)                1826
Raiders of the Lost Ark (1981)                           1500
Star Wars: Episode V - The Empire Strikes Back (1980)    1483
Godfather, The (1972)                                    1475
Schindler's List (1993)                                  1474
Shawshank Redemption, The (1994)                         1457
Matrix, The (1999)                                       1430
Saving Private Ryan (1998)                               1404
Sixth Sense, The (1999)                                  1385
Name: MovieName, dtype: int64

In [227]:
data_subset = data.sample(frac=0.10,random_state =1)
data_subset.shape

(99808, 27)

In [228]:
data_subset

,MovieID,MovieName,Adventure,Children's,Fantasy,Comedy,Romance,Drama,Action,Crime,...,Mystery,Film-Noir,Western,UserID,Ratings,TimeStamp,Gender,Age,Occupation,Zip-code
699876,1197,"Princess Bride, The (1987)",1,0,0,1,1,0,1,0,...,0,0,0,5920,4,957310879,0,25,1,05401
714034,3578,Gladiator (2000),0,0,0,0,0,1,1,0,...,0,0,0,4937,3,962645789,1,35,0,02108
663702,1032,Alice in Wonderland (1951),0,1,0,0,0,0,0,0,...,0,0,0,1697,5,974710175,0,18,4,98052
860186,780,Independence Day (ID4) (1996),0,0,0,0,0,0,1,0,...,0,0,0,242,4,976750715,0,18,4,53706
899002,1923,There's Something About Mary (1998),0,0,0,1,0,0,0,0,...,0,0,0,5120,3,962257943,1,50,7,80302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256659,471,"Hudsucker Proxy, The (1994)",0,0,0,1,1,0,0,0,...,0,0,0,5367,3,960511063,1,18,4,55344
629189,2126,Snake Eyes (1998),0,0,0,0,0,0,1,1,...,1,0,0,2894,1,971987897,1,18,4,44130
262559,3259,Far and Away (1992),0,0,0,0,1,1,0,0,...,0,0,0,5523,4,959649431,1,35,0,60187
246735,3742,"Battleship Potemkin, The (Bronenosets Potyomki...",0,0,0,0,0,1,0,0,...,0,0,0,5074,3,962435986,1,1,0,20132
482779,2433,"Civil Action, A (1998)",0,0,0,0,0,1,0,0,...,0,0,0,2129,2,974642796,1,25,5,04103

In [246]:
X = data_subset.drop(['MovieID','MovieName','UserID','Ratings','TimeStamp','Zip-code'],axis=1).values
y = data_subset['Ratings'].values

In [247]:
X

array([[ 1,  0,  0, ...,  0, 25,  1],
       [ 0,  0,  0, ...,  1, 35,  0],
       [ 0,  1,  0, ...,  0, 18,  4],
       ...,
       [ 0,  0,  0, ...,  1, 35,  0],
       [ 0,  0,  0, ...,  1,  1,  0],
       [ 0,  0,  0, ...,  1, 25,  5]], dtype=int64)

In [248]:
y

array([4, 3, 5, ..., 4, 3, 2], dtype=int64)

In [249]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X[:,19:] = scaler.fit_transform(X[:,19:])
X

array([[ 1,  0,  0, ...,  0,  0, -1],
       [ 0,  0,  0, ...,  1,  0, -1],
       [ 0,  1,  0, ...,  0, -1,  0],
       ...,
       [ 0,  0,  0, ...,  1,  0, -1],
       [ 0,  0,  0, ...,  1, -2, -1],
       [ 0,  0,  0, ...,  1,  0,  0]], dtype=int64)

In [250]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [251]:
X_train.shape,y_train.shape

((79846, 21), (79846,))

In [252]:
X_test.shape,y_test.shape

((19962, 21), (19962,))

In [258]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(max_iter=150)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)

Accuracy: 0.348011221320509

In [259]:
y_pred[:1000]

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 5, 4, 4, 4, 4, 4,
       3, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 5,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4,
       3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 3, 4, 4, 4, 4, 5, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 3, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3,
       4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4,
       4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 3, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       3, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 5, 4, 4, 4, 4,
       4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 3, 4, 5, 4, 4, 4, 4, 4, 4, 4,
       4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3,
       4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4,
       3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 5, 4, 4, 4, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 3, 5], dtype=int64)